"""add_tenant_user_id

Revision ID: 18bc7b9a2583
Revises: ca7c50200645
Create Date: 2026-08-13 22:39:15.555218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bc7b9a2583'
down_revision: Union[str, Sequence[str], None] = 'ca7c50200645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_buildings', 'floors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('property_buildings', 'total_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('property_buildings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.create_index(op.f('ix_property_buildings_organization_id'), 'property_buildings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_buildings_property_id'), 'property_buildings', ['property_id'], unique=False)
    op.alter_column('property_invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Unpaid'::character varying"))
    op.alter_column('property_invoices', 'channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Pending Payment'::character varying"))
    op.drop_index(op.f('ix_property_invoices_org'), table_name='property_invoices')
    op.create_index(op.f('ix_property_invoices_lease_id'), 'property_invoices', ['lease_id'], unique=False)
    op.create_index('ix_property_invoices_org_status', 'property_invoices', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_property_invoices_organization_id'), 'property_invoices', ['organization_id'], unique=False)
    op.alter_column('property_leases', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.drop_index(op.f('ix_property_leases_org'), table_name='property_leases')
    op.create_index('ix_property_leases_org_status', 'property_leases', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_property_leases_organization_id'), 'property_leases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_leases_tenant_id'), 'property_leases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_property_leases_unit_id'), 'property_leases', ['unit_id'], unique=False)
    op.alter_column('property_maintenance_tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Medium'::character varying"))
    op.alter_column('property_maintenance_tickets', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Open'::character varying"))
    op.alter_column('property_maintenance_tickets', 'technician',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               existing_server_default=sa.text("'Unassigned'::character varying"))
    op.create_index(op.f('ix_property_maintenance_tickets_organization_id'), 'property_maintenance_tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_maintenance_tickets_unit_id'), 'property_maintenance_tickets', ['unit_id'], unique=False)
    op.add_column('property_owners', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('property_owners', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'INDIVIDUAL'::character varying"))
    op.alter_column('property_owners', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.create_index(op.f('ix_property_owners_organization_id'), 'property_owners', ['organization_id'], unique=False)
    op.alter_column('property_ownership', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Primary'::character varying"))
    op.create_index(op.f('ix_property_ownership_organization_id'), 'property_ownership', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_ownership_owner_id'), 'property_ownership', ['owner_id'], unique=False)
    op.create_index(op.f('ix_property_ownership_property_id'), 'property_ownership', ['property_id'], unique=False)
    op.alter_column('property_properties', 'units_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('property_properties', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Active'::character varying"))
    op.drop_index(op.f('ix_property_properties_org'), table_name='property_properties')
    op.create_index('ix_property_properties_org_status', 'property_properties', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_property_properties_organization_id'), 'property_properties', ['organization_id'], unique=False)
    op.add_column('property_tenants', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('property_tenants', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Individual'::character varying"))
    op.alter_column('property_tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Active'::character varying"))
    op.drop_index(op.f('ix_property_tenants_org'), table_name='property_tenants')
    op.create_index('ix_property_tenants_org_status', 'property_tenants', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_property_tenants_organization_id'), 'property_tenants', ['organization_id'], unique=False)
    op.alter_column('property_transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Pending Audit'::character varying"))
    op.create_index(op.f('ix_property_transactions_organization_id'), 'property_transactions', ['organization_id'], unique=False)
    op.alter_column('property_units', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'VACANT'::character varying"))
    op.drop_index(op.f('ix_property_units_org'), table_name='property_units')
    op.drop_constraint(op.f('uq_property_units_org_unit_no'), 'property_units', type_='unique')
    op.create_index(op.f('ix_property_units_building_id'), 'property_units', ['building_id'], unique=False)
    op.create_index('ix_property_units_org_status', 'property_units', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_property_units_organization_id'), 'property_units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_units_property_id'), 'property_units', ['property_id'], unique=False)
    op.create_unique_constraint('uq_property_units_org_prop_unitno', 'property_units', ['organization_id', 'property_id', 'unit_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_property_units_org_prop_unitno', 'property_units', type_='unique')
    op.drop_index(op.f('ix_property_units_property_id'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_organization_id'), table_name='property_units')
    op.drop_index('ix_property_units_org_status', table_name='property_units')
    op.drop_index(op.f('ix_property_units_building_id'), table_name='property_units')
    op.create_unique_constraint(op.f('uq_property_units_org_unit_no'), 'property_units', ['organization_id', 'property_id', 'unit_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_property_units_org'), 'property_units', ['organization_id'], unique=False)
    op.alter_column('property_units', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'VACANT'::character varying"))
    op.drop_index(op.f('ix_property_transactions_organization_id'), table_name='property_transactions')
    op.alter_column('property_transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Pending Audit'::character varying"))
    op.drop_index(op.f('ix_property_tenants_organization_id'), table_name='property_tenants')
    op.drop_index('ix_property_tenants_org_status', table_name='property_tenants')
    op.create_index(op.f('ix_property_tenants_org'), 'property_tenants', ['organization_id'], unique=False)
    op.alter_column('property_tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Active'::character varying"))
    op.alter_column('property_tenants', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Individual'::character varying"))
    op.drop_column('property_tenants', 'user_id')
    op.drop_index(op.f('ix_property_properties_organization_id'), table_name='property_properties')
    op.drop_index('ix_property_properties_org_status', table_name='property_properties')
    op.create_index(op.f('ix_property_properties_org'), 'property_properties', ['organization_id'], unique=False)
    op.alter_column('property_properties', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Active'::character varying"))
    op.alter_column('property_properties', 'units_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_property_ownership_property_id'), table_name='property_ownership')
    op.drop_index(op.f('ix_property_ownership_owner_id'), table_name='property_ownership')
    op.drop_index(op.f('ix_property_ownership_organization_id'), table_name='property_ownership')
    op.alter_column('property_ownership', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Primary'::character varying"))
    op.drop_index(op.f('ix_property_owners_organization_id'), table_name='property_owners')
    op.alter_column('property_owners', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('property_owners', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'INDIVIDUAL'::character varying"))
    op.drop_column('property_owners', 'user_id')
    op.drop_index(op.f('ix_property_maintenance_tickets_unit_id'), table_name='property_maintenance_tickets')
    op.drop_index(op.f('ix_property_maintenance_tickets_organization_id'), table_name='property_maintenance_tickets')
    op.alter_column('property_maintenance_tickets', 'technician',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               existing_server_default=sa.text("'Unassigned'::character varying"))
    op.alter_column('property_maintenance_tickets', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Open'::character varying"))
    op.alter_column('property_maintenance_tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Medium'::character varying"))
    op.drop_index(op.f('ix_property_leases_unit_id'), table_name='property_leases')
    op.drop_index(op.f('ix_property_leases_tenant_id'), table_name='property_leases')
    op.drop_index(op.f('ix_property_leases_organization_id'), table_name='property_leases')
    op.drop_index('ix_property_leases_org_status', table_name='property_leases')
    op.create_index(op.f('ix_property_leases_org'), 'property_leases', ['organization_id'], unique=False)
    op.alter_column('property_leases', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.drop_index(op.f('ix_property_invoices_organization_id'), table_name='property_invoices')
    op.drop_index('ix_property_invoices_org_status', table_name='property_invoices')
    op.drop_index(op.f('ix_property_invoices_lease_id'), table_name='property_invoices')
    op.create_index(op.f('ix_property_invoices_org'), 'property_invoices', ['organization_id'], unique=False)
    op.alter_column('property_invoices', 'channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Pending Payment'::character varying"))
    op.alter_column('property_invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Unpaid'::character varying"))
    op.drop_index(op.f('ix_property_buildings_property_id'), table_name='property_buildings')
    op.drop_index(op.f('ix_property_buildings_organization_id'), table_name='property_buildings')
    op.alter_column('property_buildings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('property_buildings', 'total_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('property_buildings', 'floors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
