"""property_001_initial_schema

Revision ID: 4a51e3a65a1f
Revises: 61ad6e56b58c
Create Date: 2026-08-16 23:14:20.678501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a51e3a65a1f'
down_revision: Union[str, Sequence[str], None] = '61ad6e56b58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
