"""add_utility_charges_table

Revision ID: 89f3abfe0ac9
Revises: b7c036253ed6
Create Date: 2026-08-25 15:50:48.532805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f3abfe0ac9'
down_revision: Union[str, Sequence[str], None] = 'b7c036253ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_utility_charges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('charge_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_name', sa.String(length=150), nullable=False),
    sa.Column('tenant_email', sa.String(length=150), nullable=True),
    sa.Column('unit_location', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('breakdown', sa.Text(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'charge_id', name='uq_property_util_charge_org_charge_id')
    )
    op.create_index('ix_property_util_charges_org_status', 'property_utility_charges', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_property_utility_charges_organization_id'), 'property_utility_charges', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_utility_charges_organization_id'), table_name='property_utility_charges')
    op.drop_index('ix_property_util_charges_org_status', table_name='property_utility_charges')
    op.drop_table('property_utility_charges')
    # ### end Alembic commands ###
