"""property_001_initial_schema

Revision ID: b7c036253ed6
Revises: 4a51e3a65a1f
Create Date: 2026-08-16 23:41:44.380053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c036253ed6'
down_revision: Union[str, Sequence[str], None] = '4a51e3a65a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_buildings_prop_id'), table_name='property_buildings')
    op.create_index(op.f('ix_property_buildings_organization_id'), 'property_buildings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_buildings_property_id'), 'property_buildings', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_documents_organization_id'), 'property_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_inspections_organization_id'), 'property_inspections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_inspections_unit_id'), 'property_inspections', ['unit_id'], unique=False)
    op.drop_index(op.f('ix_property_invoices_org_id'), table_name='property_invoices')
    op.create_index(op.f('ix_property_invoices_organization_id'), 'property_invoices', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_leases_org_id'), table_name='property_leases')
    op.drop_index(op.f('ix_property_leases_tnt_id'), table_name='property_leases')
    op.create_index(op.f('ix_property_leases_organization_id'), 'property_leases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_leases_tenant_id'), 'property_leases', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_property_tickets_unit_id'), table_name='property_maintenance_tickets')
    op.create_index(op.f('ix_property_maintenance_tickets_organization_id'), 'property_maintenance_tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_maintenance_tickets_unit_id'), 'property_maintenance_tickets', ['unit_id'], unique=False)
    op.create_index(op.f('ix_property_meter_readings_organization_id'), 'property_meter_readings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_meter_readings_unit_id'), 'property_meter_readings', ['unit_id'], unique=False)
    op.create_index(op.f('ix_property_notifications_organization_id'), 'property_notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_owners_organization_id'), 'property_owners', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_ownership_own_id'), table_name='property_ownership')
    op.drop_index(op.f('ix_property_ownership_prop_id'), table_name='property_ownership')
    op.create_index(op.f('ix_property_ownership_organization_id'), 'property_ownership', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_ownership_owner_id'), 'property_ownership', ['owner_id'], unique=False)
    op.create_index(op.f('ix_property_ownership_property_id'), 'property_ownership', ['property_id'], unique=False)
    op.drop_index(op.f('ix_property_properties_org_id'), table_name='property_properties')
    op.create_index(op.f('ix_property_properties_organization_id'), 'property_properties', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_tenants_org_id'), table_name='property_tenants')
    op.create_index(op.f('ix_property_tenants_organization_id'), 'property_tenants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_transactions_organization_id'), 'property_transactions', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_units_bldg_id'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_org_id'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_prop_id'), table_name='property_units')
    op.create_index(op.f('ix_property_units_building_id'), 'property_units', ['building_id'], unique=False)
    op.create_index(op.f('ix_property_units_organization_id'), 'property_units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_units_property_id'), 'property_units', ['property_id'], unique=False)
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_units_property_id'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_organization_id'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_building_id'), table_name='property_units')
    op.create_index(op.f('ix_property_units_prop_id'), 'property_units', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_units_org_id'), 'property_units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_units_bldg_id'), 'property_units', ['building_id'], unique=False)
    op.drop_index(op.f('ix_property_transactions_organization_id'), table_name='property_transactions')
    op.drop_index(op.f('ix_property_tenants_organization_id'), table_name='property_tenants')
    op.create_index(op.f('ix_property_tenants_org_id'), 'property_tenants', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_properties_organization_id'), table_name='property_properties')
    op.create_index(op.f('ix_property_properties_org_id'), 'property_properties', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_ownership_property_id'), table_name='property_ownership')
    op.drop_index(op.f('ix_property_ownership_owner_id'), table_name='property_ownership')
    op.drop_index(op.f('ix_property_ownership_organization_id'), table_name='property_ownership')
    op.create_index(op.f('ix_property_ownership_prop_id'), 'property_ownership', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_ownership_own_id'), 'property_ownership', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_property_owners_organization_id'), table_name='property_owners')
    op.drop_index(op.f('ix_property_notifications_organization_id'), table_name='property_notifications')
    op.drop_index(op.f('ix_property_meter_readings_unit_id'), table_name='property_meter_readings')
    op.drop_index(op.f('ix_property_meter_readings_organization_id'), table_name='property_meter_readings')
    op.drop_index(op.f('ix_property_maintenance_tickets_unit_id'), table_name='property_maintenance_tickets')
    op.drop_index(op.f('ix_property_maintenance_tickets_organization_id'), table_name='property_maintenance_tickets')
    op.create_index(op.f('ix_property_tickets_unit_id'), 'property_maintenance_tickets', ['unit_id'], unique=False)
    op.drop_index(op.f('ix_property_leases_tenant_id'), table_name='property_leases')
    op.drop_index(op.f('ix_property_leases_organization_id'), table_name='property_leases')
    op.create_index(op.f('ix_property_leases_tnt_id'), 'property_leases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_property_leases_org_id'), 'property_leases', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_invoices_organization_id'), table_name='property_invoices')
    op.create_index(op.f('ix_property_invoices_org_id'), 'property_invoices', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_property_inspections_unit_id'), table_name='property_inspections')
    op.drop_index(op.f('ix_property_inspections_organization_id'), table_name='property_inspections')
    op.drop_index(op.f('ix_property_documents_organization_id'), table_name='property_documents')
    op.drop_index(op.f('ix_property_buildings_property_id'), table_name='property_buildings')
    op.drop_index(op.f('ix_property_buildings_organization_id'), table_name='property_buildings')
    op.create_index(op.f('ix_property_buildings_prop_id'), 'property_buildings', ['property_id'], unique=False)
    # ### end Alembic commands ###
